from copy import deepcopy

from race_overlay.hud_schema import HudConfig, HudThemeConfig, HudWidgetConfig


def broadcast_runner_preset() -> HudConfig:
    return HudConfig(
        theme=HudThemeConfig(
            panel_rgba=[12, 18, 28, 148],
            accent_rgba=[26, 230, 198, 255],
            text_rgba=[247, 251, 255, 255],
            font_family="sans",
            font_weight="regular",
            font_size_px=18,
            show_units=True,
        ),
        widgets=[
            HudWidgetConfig(
                "distance-ruler",
                "progress_bar",
                {"value": "distance_m"},
                "top-left",
                360,
                28,
                560,
                56,
                40,
                True,
                {"label": "Distance", "variant": "ruler", "show_current_value": True, "show_total_value": True},
            ),
            HudWidgetConfig(
                "elevation-stat",
                "stat_block",
                {"value": "altitude_m"},
                "top-left",
                44,
                146,
                160,
                86,
                30,
                True,
                {"label": "Elevation", "unit": "M"},
            ),
            HudWidgetConfig(
                "distance-stat",
                "stat_block",
                {"value": "distance_m"},
                "top-left",
                44,
                320,
                210,
                88,
                30,
                True,
                {"label": "Distance", "unit": "KM", "decimals": 2},
            ),
            HudWidgetConfig(
                "heart-rate-stat",
                "stat_block",
                {"value": "heart_rate_bpm"},
                "top-right",
                1100,
                132,
                138,
                82,
                30,
                True,
                {"label": "Heart rate", "unit": "BPM", "align": "right"},
            ),
            HudWidgetConfig(
                "pace-chip",
                "metric_card",
                {"value": "pace_seconds_per_km"},
                "bottom-right",
                980,
                560,
                120,
                72,
                20,
                True,
                {"label": "Pace", "variant": "compact"},
            ),
            HudWidgetConfig(
                "cadence-chip",
                "metric_card",
                {"value": "cadence_spm"},
                "bottom-right",
                1110,
                560,
                120,
                72,
                20,
                True,
                {"label": "Cadence", "variant": "compact"},
            ),
            HudWidgetConfig(
                "elapsed-chip",
                "metric_card",
                {"value": "elapsed_seconds"},
                "bottom-right",
                980,
                642,
                120,
                72,
                20,
                True,
                {"label": "Elapsed", "variant": "compact"},
            ),
            HudWidgetConfig(
                "speed-chip",
                "metric_card",
                {"value": "speed_mps"},
                "bottom-right",
                1110,
                642,
                120,
                72,
                20,
                True,
                {"label": "Speed", "variant": "compact"},
            ),
            HudWidgetConfig(
                "route-map",
                "route_map",
                {"value": "route_points"},
                "top-left",
                26,
                514,
                180,
                180,
                20,
                True,
                {"label": "", "shape": "circle", "show_panel": True},
            ),
        ],
    )


def apply_legacy_field_visibility(config: HudConfig, fields: dict[str, bool]) -> HudConfig:
    updated = deepcopy(config)
    visibility_map = {
        "distance-ruler": fields.get("distance", True),
        "elevation-stat": fields.get("distance", True),
        "distance-stat": fields.get("distance", True),
        "heart-rate-stat": fields.get("heart_rate", True),
        "pace-chip": fields.get("pace", True),
        "cadence-chip": fields.get("cadence", True),
        "elapsed-chip": fields.get("elapsed", True),
        "speed-chip": fields.get("speed", True),
        "route-map": fields.get("mini_map", True),
    }
    for widget in updated.widgets:
        if widget.id in visibility_map:
            widget.visible = visibility_map[widget.id]
    return updated
